### ISSUE TITLE
Debajo del footer aparece una linea blanca

### ISSUE THREAD

**Issue by jforni** [JeremiasJM/front-gestion-restaurante#24]
Debajo del footer aparece una línea blanca gruesa que no queda estéticamente bien, ya que da la sensación de que falta algo.
Adjunto imagen:
![image](https://github.com/user-attachments/assets/97f0b0d2-1746-4970-9d74-c24a8a27d376)

**Comment by georginacostilla** [comment]
Error de diseño corregido desde la rama Dev y actualizado en main. 
Deploy: https://rolling-food-reserva.vercel.app/
